version: "3"

services:
  mysqldb:
   container_name: mysqldbaba
   image: mysql:8
   restart: unless-stopped
   ports:
    - 3307:3306
   environment:
    MYSQL_DATABASE: achatdb
    MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
   volumes:
     - /home/mysql/data:/var/lib/mysql --user 1000

  spring_app:
   image: mohamedbenmiled/achat234
   container_name: achat23
   restart: on-failure
   ports:
    - 8089:8089
   depends_on:
    - mysqldb
